### ISSUE TITLE
Safari cannot download this file

### ISSUE THREAD

**Issue by dwinc** [alexandercerutti/passkit-generator#92] opened 2021-12-03 14:51 UTC
Hi Alexander,
I have been running your passkit-generator successfully for over 2 years now (probably a 1st gen version) and always worked like a charm.
However recently I received complaints from users that the pass download no  longer works. I tested it on my iphone and I get the error: Safari cannot download this file.
The file download does work (on a PC) .. and after some 'googling' I read various reasons that could be at play.
My instinct says it might have something to do with the certificates. What are your thoughts?

**Comment by alexandercerutti** [comment] 2021-12-03 14:56
Hey @dwinc, sounds weird. I don't actually have any hint to think to a valid reason for this to happen. Are you able to reproduce the issue? If so, what is the server response? Does this happen for all the users?

Anyway, I suggest you attempting to upgrade to the latest version of passkit-generator, because previous have been deprecated (up to 2.0.5 included).

**Comment by alexandercerutti** [comment] 2021-12-05 12:44
@dwinc were you able to figure out what is happening? Can I be helpful somehow else or can I close this? Let me know.

**Closed** 2021-12-08 15:17 UTC
Labels: question

**Comment by kyle-ssg** [comment] 2022-11-27 12:41
Just incase someone sees this, I don't think this is the case with the writer of the issue but this is the message you get if you enter an invalid passTypeIdentifier/teamIdentifier. In my case I mistakenly edited the examplePass's pass.json and not the exampleBooking's.
